/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as ApiEditImageRouteImport } from './routes/api/edit-image'
import { Route as ApiVideoStyleRouteImport } from './routes/api/video-style'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditImageRoute = ApiEditImageRouteImport.update({
  id: '/api/edit-image',
  path: '/api/edit-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoStyleRoute = ApiVideoStyleRouteImport.update({
  id: '/api/video-style',
  path: '/api/video-style',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/video-style': typeof ApiVideoStyleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/video-style': typeof ApiVideoStyleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/video-style': typeof ApiVideoStyleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/coach' | '/api/edit-image' | '/api/video-style'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/coach' | '/api/edit-image' | '/api/video-style'
  id: '__root__' | '/' | '/api/coach' | '/api/edit-image' | '/api/video-style'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCoachRoute: typeof ApiCoachRoute
  ApiEditImageRoute: typeof ApiEditImageRoute
  ApiVideoStyleRoute: typeof ApiVideoStyleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edit-image': {
      id: '/api/edit-image'
      path: '/api/edit-image'
      fullPath: '/api/edit-image'
      preLoaderRoute: typeof ApiEditImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-style': {
      id: '/api/video-style'
      path: '/api/video-style'
      fullPath: '/api/video-style'
      preLoaderRoute: typeof ApiVideoStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCoachRoute: ApiCoachRoute,
  ApiEditImageRoute: ApiEditImageRoute,
  ApiVideoStyleRoute: ApiVideoStyleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
