/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFindClipsRouteImport } from './routes/api/find-clips'
import { Route as ApiIdentifyEditRouteImport } from './routes/api/identify-edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFindClipsRoute = ApiFindClipsRouteImport.update({
  id: '/api/find-clips',
  path: '/api/find-clips',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdentifyEditRoute = ApiIdentifyEditRouteImport.update({
  id: '/api/identify-edit',
  path: '/api/identify-edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/find-clips': typeof ApiFindClipsRoute
  '/api/identify-edit': typeof ApiIdentifyEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/find-clips': typeof ApiFindClipsRoute
  '/api/identify-edit': typeof ApiIdentifyEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/find-clips': typeof ApiFindClipsRoute
  '/api/identify-edit': typeof ApiIdentifyEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/find-clips' | '/api/identify-edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/find-clips' | '/api/identify-edit'
  id: '__root__' | '/' | '/api/find-clips' | '/api/identify-edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFindClipsRoute: typeof ApiFindClipsRoute
  ApiIdentifyEditRoute: typeof ApiIdentifyEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/find-clips': {
      id: '/api/find-clips'
      path: '/api/find-clips'
      fullPath: '/api/find-clips'
      preLoaderRoute: typeof ApiFindClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/identify-edit': {
      id: '/api/identify-edit'
      path: '/api/identify-edit'
      fullPath: '/api/identify-edit'
      preLoaderRoute: typeof ApiIdentifyEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFindClipsRoute: ApiFindClipsRoute,
  ApiIdentifyEditRoute: ApiIdentifyEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
